### ISSUE TITLE
Python 3 error

### ISSUE THREAD

**Issue by mrtpols** [depuits/elro_connects_docker#1]
Dear Developer,

If i run your dockerfile i get an error, related to python 3.10 and higher.
I have change your dockerfile for my self in FROM python:3.9 and its fine again.

**Comment by depuits** [comment]
Thank you for reporting the issue. This is more an issue with the elro connects code which is not compatible with python 3.10. I've made an [issue](https://github.com/dib0/elro_connects/issues/16) in that project but have currently fixed the container by specifying the python 3.9 version.
